#!/usr/bin/env python3
"""
AUTO-GENERATED FILE – DO NOT EDIT MANUALLY.
This file is generated by the sync2_aliases.py tool.
It contains all dynamic imports, group themes/icons, and group help registration code.
"""

# [AUTO-GENERATED COMMAND IMPORTS START]
{command_imports_block}
# [AUTO-GENERATED COMMAND IMPORTS END]


# [AUTO-GENERATED GROUP THEMES AND ICONS START]
{group_themes_icons_block}
# [AUTO-GENERATED GROUP THEMES AND ICONS END]


def register_dynamic_groups():
    """Register all dynamic command groups with the main CLI."""
    from starshipagentic.cli import main, enhance_group_help
    import importlib
    GROUP_NAMES = {group_names_block}
    for group in GROUP_NAMES:
        mod = importlib.import_module(f'starshipagentic.commands.{group}')
        group_obj = getattr(mod, f'{group}_group', None)
        if group_obj is None:
            continue
        enhanced = enhance_group_help(group_obj, group)
        main.add_command(enhanced, group)
